import { heroui } from '@heroui/react'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#c0c1ff',
        'surface-container-lowest': '#090d1d',
        'inverse-primary': '#4b4dcf',
        'on-secondary-fixed': '#301400',
        'secondary-container': '#9e5100',
        'on-primary-fixed-variant': '#3131b6',
        'on-surface': '#dfe1f9',
        'surface-container-low': '#171b2c',
        'secondary-fixed': '#ffdcc4',
        'on-tertiary-fixed': '#0f2000',
        'on-background': '#dfe1f9',
        'on-tertiary': '#1d3700',
        'primary-fixed': '#e1e0ff',
        'tertiary-fixed': '#97fc00',
        'error-container': '#93000a',
        error: '#ffb4ab',
        'on-surface-variant': '#c7c5d6',
        'surface-bright': '#35384b',
        'surface-tint': '#c0c1ff',
        'inverse-surface': '#dfe1f9',
        'tertiary-fixed-dim': '#84dd00',
        'on-primary-fixed': '#07006c',
        outline: '#908fa0',
        'surface-dim': '#0f1223',
        'on-tertiary-fixed-variant': '#2c5000',
        'surface-container': '#1b1f30',
        'on-error': '#690005',
        'on-primary': '#150aa2',
        'surface-container-highest': '#303446',
        'tertiary-container': '#5fa200',
        'surface-container-high': '#25293b',
        background: '#0f1223',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#ffb781',
        'on-tertiary-container': '#183000',
        'on-secondary': '#4e2500',
        'surface-variant': '#303446',
        surface: '#0f1223',
        secondary: '#ffb781',
        'outline-variant': '#464554',
        'on-secondary-fixed-variant': '#703800',
        'on-secondary-container': '#ffdec8',
        'primary-container': '#8083ff',
        'on-primary-container': '#0e0095',
        'inverse-on-surface': '#2c2f41',
        primary: '#c0c1ff',
        tertiary: '#84dd00',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [heroui()],
}
